/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Street = (props) => {
  const group = useRef();
  const { nodes, materials } = useGLTF("/assets/street/street.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[0, 0.1, 4.3]}
        scale={[9.02, 1, 14.55]}
      />
      <mesh
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={nodes.Cube025.material}
        position={[10.46, 0, 4.43]}
        scale={[1.31, 0.32, 14.74]}
      />
      <mesh
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={nodes.Cube026.material}
        position={[10.4, 0.73, 9.08]}
        scale={[0.88, 1, 0.66]}
      />
      <mesh
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={nodes.Cube028.material}
        position={[10.4, 0.73, -4.41]}
        scale={[0.88, 1, 0.66]}
      />
      <group position={[9.02, 11.6, 9.12]} scale={[1.44, 0.08, 0.59]}>
        <mesh
          receiveShadow
          geometry={nodes.Cube030_1.geometry}
          material={nodes.Cube030_1.material}
        />
        <mesh
          receiveShadow
          geometry={nodes.Cube030_2.geometry}
          material={nodes.Cube030_2.material}
        />
      </group>
      <group position={[9.02, 11.6, -4.37]} scale={[1.44, 0.08, 0.59]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030_1.geometry}
          material={nodes.Cube030_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030_2.geometry}
          material={nodes.Cube030_2.material}
        />
      </group>
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={materials["Material.002"]}
        position={[1.46, 11.49, 4.29]}
        scale={[10.96, 12.4, 14.83]}
      /> */}
    </group>
  );
}

useGLTF.preload("/street.glb");

export default Street
